[package]
name = "rekvizitai_lt_parser"
version = "0.2.0"
authors = ["hitwright"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.7.0"
actix-web = "4.2.1"
clap = { version = "4.0.27", features = ["derive"] }
env_logger = "0.10.0"
file_diff = "1.0.0"
futures = "0.3.25"
html5ever = "0.26.0"
image = "0.24.5"
json = "0.12.4"
leptess = "0.13.4"
log = "0.4.17"
regex = "1.7.0"
reqwest = "0.11.13"
serde = { features = ["derive"], version = "1.0.148" }
soup = "0.5.1"
tempfile = "3.3.0"
