[package]
name = "rekvizitai_lt_parser"
version = "0.1.0"
authors = ["hitwright"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "*"
actix-web = "*"
env_logger = "*"
file_diff = "*"
futures = "*"
html5ever = "*"
image = "*"
json = "*"
leptess = "*"
log = "*"
regex = "*"
reqwest = "0.9.24"
serde = "*"
soup = "*"
tempfile = "*"
